on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create the release

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./code
        
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          npm run build --if-present       
          zip --junk-paths sttf-url-generator ./dist
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  
          asset_path: ./sttf-url-generator.zip
          asset_name: sttf-url-generator.zip
          asset_content_type: application/zip
